version: "3.9"

services:
  adora-api:
    build: .
    container_name: adora_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # live code reload if needed
